### ISSUE TITLE
populate entire GC Landsat/Sentinel catalogs

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/RD-WATCH#2]
Add a new management command/update the existing one to accept an ROI (GeoJSON) and ingest interesting Landsat and Sentinel data

**Comment by banesullivan** [comment]
I have local scripts that currently produce the CSV file that is used to pull data - these should be included in the command

**Comment by banesullivan** [comment]
We may actually want to expose this as a POST endpoint

**Comment by banesullivan** [comment]
Perhaps even, we could create custom models in this project that trigger a task to do the ingest such that we're aware of which regions we have previously ingested.

**Comment by aashish24** [comment]
@banesullivan is this still relevant and active?

**Comment by banesullivan** [comment]
I'm still working on this/deciding if I will be including it

**Comment by banesullivan** [comment]
We are no longer using Google cloud
