### ISSUE TITLE
Set correct production instance as api_url

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/RD-WATCH#47]
@AlmightyYakob, could we set this up so that if using the `rgd_watch_client` plugin, it overrides the `api_url` by default?

**Comment by AlmightyYakob** [comment]
I'm not sure I understand the question, as `api_url` is passed into `create_rgd_client`. Do you mean change the default value for that parameter?

**Comment by AlmightyYakob** [comment]
Also to clarify, each plugin is passed a requests session in it's `__init__`, so it could change the base url for that session, but that's limited to that specific plugin (i.e. it couldn't change any other plugin sessions).

**Comment by banesullivan** [comment]
Perhaps upstream we could have a `DEFAULT_API_URL` variable and `rgd_watch_client` overrides that on import?

**Comment by banesullivan** [comment]
The WATCH plugin should *never* be used with another project-plugin so this should be fine

**Comment by AlmightyYakob** [comment]
I'm confused as to why you couldn't simply supply the `api_url` as an argument of `create_rgd_client`. Would this just be a convenience, so that you could just call `create_rgd_client` without needing to know much about the production watch deployment?

If that's the case, I'd suggest we just add a `create_watch_client` method in the watch client itself, which just wraps `create_rgd_client`.

**Comment by banesullivan** [comment]
Yes, this is purely for convenience - we want to make it as easy as possible for the WATCH users to use the python client to connect to the server

> If that's the case, I'd suggest we just add a create_watch_client method in the watch client itself, which just wraps create_rgd_client.

Let's go with this approach, can you implement this ASAP?

**Comment by AlmightyYakob** [comment]
> Yes, this is purely for convenience - we want to make it as easy as possible for the WATCH users to use the python client to connect to the server
> 
> > If that's the case, I'd suggest we just add a create_watch_client method in the watch client itself, which just wraps create_rgd_client.
> 
> Let's go with this approach, can you implement this ASAP?

Sure
