### ISSUE TITLE
Data ingestion takes too long

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/RD-WATCH#52]
The worldview ingest routine timed out after 6 hours (GitHub's limit): https://github.com/ResonantGeoData/RD-WATCH/runs/4516298970?check_suite_focus=true

The bottleneck is the RGD server -- how can we speed this up? Perhaps parallelizing the post requests and spawning a huge pool of threads?

@mcovalt, any thoughts?

**Comment by mcovalt** [comment]
> Perhaps parallelizing the post requests and spawning a huge pool of threads?

Yup, that's the quickest way to do it. Thankfully (to your planning) we have iterators all the way down so a [ThreadPoolExecutor](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor) is a simple means to an end here.

**Comment by mcovalt** [comment]
I'd limit the number of requester threads to 50% of the threads Unicorn is started with. If we hit timeout errors doing that then we need to begin focusing on what can be done on the backend. Most likely that would force our hand to stand up a PostgreSQL connection pooler.

**Comment by banesullivan** [comment]
FYI, the dry run (iterating over the collections but not posting to RGD) takes this long:

![Screen Shot 2021-12-14 at 8 11 26 PM](https://user-images.githubusercontent.com/22067021/146117299-3cc887ba-f097-4bce-8aff-e14713299284.png)

**Comment by banesullivan** [comment]
Solution is to run locally.
