### ISSUE TITLE
Paginate evaluations

### ISSUE THREAD

**Issue by mcovalt** [ResonantGeoData/RD-WATCH#89]
Currently all evaluations are pulled into the sidebar. We'll need to paginate this. It would be cool to [virtualize the large list](https://vuejs.org/guide/best-practices/performance.html#virtualize-large-lists) and have that work in tandem with the pagination. The evaluation buttons are all the same size, so getting a count of all evaluations to buffer the scroll area should be doable.

**Comment by mvandenburgh** [comment]
Closed by #128
