### ISSUE TITLE
Drop `SatelliteImage` model

### ISSUE THREAD

**Issue by mcovalt** [ResonantGeoData/RD-WATCH#94]
The [`SatelliteImage` model](https://github.com/ResonantGeoData/RD-WATCH/blob/314088103c819aecefbe41f02c556c21d852dc7f/django/src/rdwatch/models/satellite_image.py) is populated during ingest to create a catalog of information required to read a remote image. This information is captured by scraping various STAC API servers at ingest time. This issue seeks to fully rely on these STAC API servers rather than duplicating their information.

## Currently

[During ingest](https://github.com/ResonantGeoData/RD-WATCH/blob/314088103c819aecefbe41f02c556c21d852dc7f/django/src/rdwatch/management/commands/ingest.py#L278-L308), STAC API servers are scraped to fetch relevant satellite images. The two modules [`rdwatch.utils.stac_search`](https://github.com/ResonantGeoData/RD-WATCH/blob/314088103c819aecefbe41f02c556c21d852dc7f/django/src/rdwatch/utils/stac_search.py) and [`rdwatch.utils.satellite_bands`](https://github.com/ResonantGeoData/RD-WATCH/blob/314088103c819aecefbe41f02c556c21d852dc7f/django/src/rdwatch/utils/satellite_bands.py) hold the logic to make these STAC API queries.

To read a satellite image tile, a request is made to [`/api/satellite-image/tile/<int:z>/<int:x>/<int:y>.webp`](https://github.com/ResonantGeoData/RD-WATCH/blob/314088103c819aecefbe41f02c556c21d852dc7f/django/src/rdwatch/urls.py#L29-L32) with the follow URL query parameters:
- **constellation**: One of `L8` or `S2` indicating whether we're pulling images from Landsat 8 or Sentinel 2
- **level**: One of `1C` or `2A` to indicate the processing level of the source imagery
- **spectrum**: Indicating the [common name of the band](https://github.com/stac-extensions/eo#common-band-names) the tile should provide
- **timestamp**: a time *around* when the satellite image was captured. This will not be precise, but it is expected the source imagery was captured within about an hour window around the provided timestamp.

The [view](https://github.com/ResonantGeoData/RD-WATCH/blob/314088103c819aecefbe41f02c556c21d852dc7f/django/src/rdwatch/views/tile.py#L98-L136) then redirects to [`/api/satellite-image/<int:pk>/tile/<int:z>/<int:x>/<int:y>.webp`](https://github.com/ResonantGeoData/RD-WATCH/blob/314088103c819aecefbe41f02c556c21d852dc7f/django/src/rdwatch/urls.py#L33-L37). This is done so the approximate timestamp will not invalidate cached requests to the same tile.

## Expected behavior

The `SatelliteImage` model is dropped and STAC API scraping during ingest is removed.

The API interface to `/api/satellite-image/tile/<int:z>/<int:x>/<int:y>.webp` stays the same.

In the associated view, the relevant STAC API will be queried with the two modules `rdwatch.utils.stac_search` and `rdwatch.utils.satellite_bands` at request time. The view then redirects to some internal URL that uniquely identifies the source imagery, perhaps even to the same path with a precise timestamp.

**Comment by mvandenburgh** [comment]
> The API interface to /api/satellite-image/tile/<int:z>/<int:x>/<int:y>.webp stays the same.

@mcovalt I attempted this, and I'm running into a problem - AFAIK, the `bbox` attribute of `SatelliteImage` is only available at ingest time. Every other parameter needed to query the STAC API for a given satellite image is provided in the current interface for that endpoint. If I just exclude the `bbox` parameter from the STAC API calls I moved into the endpoint, it seems that the assumption that the image with the timestamp closest to the timestamp provided in the endpoint request no longer holds because there could be some images that have a closer timestamp but a different bounding box. From what I can tell, there's no way to figure out which image from the STAC response corresponds to the parameters the user passed unless the user includes a bounding box in their request.

**Comment by mcovalt** [comment]
The bounding box can actually be determined from the parameters `x`, `y`, and `z` in the URL.

The [mercantile](https://github.com/mapbox/mercantile) Python package can assist with this. For example, on the request to:

`/api/satellite-image/tile/10/486/332.webp`

```python
>>> import mercantile
>>> x = 486
>>> y = 332
>>> z = zoom = 10
>>> mercantile.bounds(x, y, z)
LngLatBbox(west=-9.140625, south=53.120405283106564, east=-8.7890625, north=53.33087298301705)
```
